### ISSUE TITLE
Wrong font path

### ISSUE THREAD

**Issue by marianzburlea** [catezee/my-cv#1]
Currently in `my-cv/src/_component/font/icon-font.scss` you have `url('fonts/my-cv.***`
Your font files are present in `_asset/font/ ` which gets converted into `asset/font` by pug into the `tmp` folder.

You want to update you path to `url('/asset/font/my-cv.***`

**Comment by marianzburlea** [comment]
@catezee , it could be the font size of the icon or the size of the box.

**Comment by catezee** [comment]
It worked. Thanks a lot, Marian!

**Comment by marianzburlea** [comment]
You should close #1 issue
